### ISSUE TITLE
Lrelease give error

### ISSUE THREAD

**Issue by Tellie** [bitwiseworks/qttools-os2#2]
This is wqith QT5 v5.15.2

When do f.e lrelease-qt5 src.pro i get the next output.
lrelease-qt5 src.pro
sh.exe: 1: C:/usr/bin/lprodump.exe: not found
sh.exe: 1: C:/usr/bin/lrelease.exe: not found

**Comment by dmik** [comment]
The above problem has been fixed by the above commit. I will just add the Fedora patch to our .spec then to make it completely fixed.
